### ISSUE TITLE
GitHub Token for Travis CI Pro - What Scope?

### ISSUE THREAD

**Issue by framerate** [tombell/travis-ci-status#35]
It's not listed what scope is necessary for Travis CI Pro's auth token. Using default settings doesn't seem to be working.

**Comment by framerate** [comment]
It started working randomly!, but I'd still like to know what scope you're requesting so I can keep my security in check!

Thanks!

**Comment by magalhas** [comment]
There's not any scope set on the authenticate request, so I guess the default one is being used (if there's one).

**Comment by tombell** [comment]
For Travis Pro, you would need private repository access in the scope of the token.
