### ISSUE TITLE
Error: Object {file: "not found"} in Pro repo

### ISSUE THREAD

**Issue by plttn** [tombell/travis-ci-status#38]
atom v0.176, up to date version of ci-status. 

Offending line is `build-status-view.coffee:117`.

**Comment by magalhas** [comment]
Are you using Travis Pro account?

**Comment by plttn** [comment]
Yes. Token with repo/public_repo/gist scope is in my settings.

It loads the status of my nonpro repos, so I know it's not the entire
package failing.

**Comment by magalhas** [comment]
Atm I don't have a pro account which makes it a lot harder to debug this issues. I think I'll contact Travis to check if they can get me a Pro account for development purposes.
