### ISSUE TITLE
Include a screenshot on README?

### ISSUE THREAD

**Issue by stevemao** [tombell/travis-ci-status#42]

**Comment by magalhas** [comment]
It seems like a good idea. Mind creating a PR?

**Comment by stevemao** [comment]
![screen shot 2015-03-11 at 9 33 06 am](https://cloud.githubusercontent.com/assets/6316590/6586951/762aa200-c7d2-11e4-9b6f-5d24b767aaed.png)

![screen shot 2015-03-11 at 9 32 30 am](https://cloud.githubusercontent.com/assets/6316590/6586952/762c0820-c7d2-11e4-8503-18e12ed4f385.png)

Do they look good to you? Sorry I don't have any project that's fail at the moment.

**Comment by stevemao** [comment]
Or maybe just show the bottom bar

![screen shot 2015-03-11 at 9 41 37 am](https://cloud.githubusercontent.com/assets/6316590/6586991/e21737b2-c7d2-11e4-99a2-61cd6515c323.png)

**Comment by magalhas** [comment]
I think I prefer the smaller version.

**Comment by stevemao** [comment]
The reason I'm posting here is because it took me a while to find where the travis icon was. It doesn't show up on a project that is not set up on https://travis-ci.org/ (instead of a grayed out icon which they use on markdown). So I think a full picture of atom might help.

This might be very obvious to you but probably not too obvious to users.

So I think this should help user find where the icon is and if they can't find it, fire a bug ticket or something like that.
