### ISSUE TITLE
Leave the icon grayed out when project is not setup onhttps://travis-ci.org

### ISSUE THREAD

**Issue by stevemao** [tombell/travis-ci-status#44]
Currently if a project is not set up on https://travis-ci.org, the travis icon is hidden. I think its better to leave it grayed out because

1. user knows this plugin is installed properly
2. it reminds user to setup the project on https://travis-ci.org
3. it makes it consistent with travis badge on README.md

**Comment by tombell** [comment]
Personally I don't use travis-ci for every project, not everything is open source and tested on travis-ci. I only want to see the icon if it's running on travis-ci.
