### ISSUE TITLE
package not shwing up at all in Atom 1.12.7 on Mac

### ISSUE THREAD

**Issue by Apollon77** [tombell/travis-ci-status#90]
After installing and also restarting and also re-adding project folders nothing is shown in Atom-IDE. Also the commands are not found in palette ... any idea? YOur latest version seems to fail building on Github

**Comment by danbohea** [comment]
^^ This. Is this package maintained any more?

**Comment by ghost1227** [comment]
It's still maintained. It's also showing up for me in 1.13.x and 1.14.x series...

**Comment by danbohea** [comment]
This is fixed for me now on Atom 1.14.3. Top work.
